### ISSUE TITLE
Read- and write streams

### ISSUE THREAD

**Issue by felixSchl** [purescript-node/purescript-node-fs#13]
Node's `fs` module's `createReadStream` and `createWriteStream` are missing.
How would they fit into the purescript way of doing things? Or more generally,
I guess - how would the whole `EventEmitter` concept fit into purescript. Essentially,
we need to wrap up events somehow to tap into what's happening to the stream.

**Comment by hdgarrood** [comment]
There is purescript-node-streams: http://pursuit.purescript.org/packages/purescript-node-streams/0.1.1/docs/Node.Stream so I suppose it should be fairly straightforward to create bindings to `createReadStream` and `createWriteStream` using it.
