### ISSUE TITLE
`mkdir` uses mode 1411, not 777

### ISSUE THREAD

**Issue by hdgarrood** [purescript-node/purescript-node-fs#14]
Because `mkdir` uses a file mode of 777 decimal (as opposed to 777 octal), it will create directories that the owner is not allowed to write into (amongst other things). The created directory actually ends up having permissions 1411, since 777 in decimal is 1411 in octal.

I think the fix should be simply to get #11 merged. Is there anything I can do to help with this?

**Comment by michaelficarra** [comment]
It looks like that PR is ready to go. A maintainer should just merge it.

**Comment by hdgarrood** [comment]
Awesome, thanks. Done.
