### ISSUE TITLE
Extract callback type, make monad instance?

### ISSUE THREAD

**Issue by felixSchl** [purescript-node/purescript-node-fs#17]
Since doing async using callbacks is the de facto in node land, I was wondering if it was time to extract the [`type Callback`](https://github.com/purescript-node/purescript-node-fs/blob/master/src/Node/FS/Async.purs#L91) into it's own module, slap a monad instance onto it or integrate it easily with [purescript-aff](https://github.com/slamdata/purescript-aff) or [contT](http://pursuit.purescript.org/?q=runcontt)? It would be great to get something like the aff monad just "out of the box" without some [guff like this](https://github.com/felixSchl/kopeer/blob/purescript/src/Internal/Aff.purs#L11) in order to write "nice looking" async code.

**Comment by garyb** [comment]
I'd probably build a separate library on top of this to provide the actions via `Aff` actually, as then people have the choice.

I'm all for an `Aff` version of these things though, I'd certainly prefer to use that formulation myself. If you want to go ahead and work on something like `purescript-node-fs-aff` I'd be happy to accept it into the organization.

**Comment by felixSchl** [comment]
I hear you, we could also have a promise based wrapper. It would be arbitrary to choose one. I will throw together such a library, shouldn't be more than a hundred lines of boilerplate code, really.

**Comment by felixSchl** [comment]
@garyb I have made start on this: [felixSchl/purescript-node-fs-aff](https://github.com/felixSchl/purescript-node-fs-aff). It's a very thin wrapper around all async methods. Feedback very welcome. I had to muck around with `Node.FS.Async.exists` because it's callback-handler is missing the `FS` effect from it's signature, causing `occurs check fails` errors when compiling. I will hand in a PR to fix that when I get around to it.

**Comment by felixSchl** [comment]
I have now explicitly annotated the exported types and did a copy and paste job on the comments. If that's a problem, I don't mind rephrasing.

**Comment by garyb** [comment]
No, that's great if they still make sense!

I've invited you to the org so you should have permission to move the repository over if you want to do that. If you'd rather keep it under your own name, that's fine too. Thanks for working on this, :thumbsup:

**Comment by felixSchl** [comment]
Cool, thanks for the invitation, I have moved it over to the organisation now.

**Comment by felixSchl** [comment]
@garyb Could I get write access to the repo or do we have to go through the PR for each change? I have added an example, some docs and updated the gulpfile.

**Comment by garyb** [comment]
If you still have issues when you try next time, perhaps delete your local git repo and checkout again.

**Comment by felixSchl** [comment]
I checked the settings for the organization and the `fs-aff` team has no repositories assigned to it, could you assign `purescript-node-fs-aff` to the team?

**Comment by garyb** [comment]
That's done now. Strange that it didn't put it there by default!

**Comment by felixSchl** [comment]
Cheers :)
