### ISSUE TITLE
Add to Pursuit?

### ISSUE THREAD

**Issue by paf31** [purescript-node/purescript-node-fs#20]

**Comment by hdgarrood** [comment]
:+1:

**Comment by hdgarrood** [comment]
I'll do this, as well as `node-path`

**Comment by hdgarrood** [comment]
http://pursuit.purescript.org/packages/purescript-node-path/0.4.0

**Comment by hdgarrood** [comment]
I meant http://pursuit.purescript.org/packages/purescript-node-fs/0.8.1

**Comment by paf31** [comment]
:+1: Thanks!
