### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by hdgarrood** [purescript-node/purescript-node-fs#24]
Hi @garyb 

Over the last day or so I have pushed a few commits to master, including @timbod7's PR. I think it might be good to publish a new release soon, perhaps once https://github.com/purescript-node/purescript-node-buffer/pull/8 is merged or closed? Anyway I just wanted to give you a heads up in case you want to review anything.

**Comment by garyb** [comment]
Sure thing - I've not really been staying on top of the changes and discussion, but I agree with all of the comments of yours I have seen, so please do go ahead!

**Comment by hdgarrood** [comment]
Super. :)
