### ISSUE TITLE
Use `EffectFnX` functions internally

### ISSUE THREAD

**Issue by hdgarrood** [purescript-node/purescript-node-fs#28]
To prevent issues like #27 from occurring again.

**Comment by paf31** [comment]
:+1:

**Comment by artemisSystem** [comment]
From what i can tell, this issue is about using (what's now called) `Effect.Uncurried` (`EffectFnX`) instead of `FnX` and `mkEffect`. The use of `mkEffect` prevents things like #27 by my understanding, but it's still an old and convoluted way of doing things. Perhaps we could switch over to `EffectFnX` at the same time as changes for #19 are made.

**Comment by JordanMartinez** [comment]
I was thinking the same thing when I reviewed your other PR. We should be using `EffectFnX` now.

**Comment by hdgarrood** [comment]
My intention when I created this was only to change the implementations internally, not to change the type signatures of any exported functions - I don't think we should use `EffectFn` in the exported functions in this library.

**Comment by artemisSystem** [comment]
Agreed

**Comment by colinwahl** [comment]
I ran into a case where the current unsafe `mkEffect` util causes a runtime error when running this code through [purescript-backend-optimizer](https://github.com/aristanetworks/purescript-backend-optimizer).

I'd be happy to make this change if no one else is working on it at the moment.

**Comment by JordanMartinez** [comment]
I'm up for making this breaking change to this library outside of the normal ecosystem breakage. With the advent of `purs-backend-es`, some things can't be optimized without this.

**Comment by colinwahl** [comment]
This shouldn't be a breaking change - none of the values whose types are changing are exported, and the exported values all retain their same types.

**Comment by JordanMartinez** [comment]
> This shouldn't be a breaking change - none of the values whose types are changing are exported, and the exported values all retain their same types.

Oh nice! I wasn't aware of that.
