### ISSUE TITLE
0.9.1 Compatibility

### ISSUE THREAD

**Issue by bkonkle** [purescript-node/purescript-node-fs#29]
Compatibility with 0.9.1 appears to be blocked until the `purescript-datetime` rewrite is complete.

The only other issue I can see is changing `import Data.Maybe.Unsafe (fromJust)` to `import Data.Maybe (fromJust)`. I'll include that in a PR once `purescript-datetime` is ready. 👍

**Comment by garyb** [comment]
Hopefully the `datetime` limbo will end soon, it's just waiting a review before release... assuming the review outcome is good :wink:

**Comment by kika** [comment]
what is necessary to update the version tag to something different from current?

**Comment by hdgarrood** [comment]
Just someone to find 10 minutes to do it is all. In the meantime you can point to `master` or a specific commit.

**Comment by paf31** [comment]
@hdgarrood Is anything stopping us from making a 1.0 release? I can do it if not.

**Comment by hdgarrood** [comment]
Not that I'm aware of. I was planning on doing it tomorrow but sure, go ahead :)

**Comment by garyb** [comment]
I've made a release now.
