### ISSUE TITLE
Errors in some APIs can't be handled

### ISSUE THREAD

**Issue by cprussin** [purescript-node/purescript-node-fs#42]
For example, in `Node.FS.Stream`, `createReadStream` has the type:

```purescript
createReadStream :: FilePath -> Effect (Readable ())
```

But the Node API can raise an exception, for instance, if the file doesn't exists.  Likely the type should be:

```purescript
createReadStream :: FilePath -> Effect (Either Error (Readable ()))
```

Is there any other solution that would be preferred here over catching the exception and returning an `Either`?

**Comment by hdgarrood** [comment]
I think it's best left as-is, because the current type best matches the Node API. If downstream libraries want to provide a more ergonomic interface that's fine, but the policy for the libraries in this org is that we try to wrap the node APIs as closely and in a minimally opinionated manner, so that they remain useful for as many use cases as possible.

**Comment by hdgarrood** [comment]
I don't think it's accurate to say that errors can't be handled, by the way: [`purescript-exceptions`](https://pursuit.purescript.org/packages/purescript-exceptions/4.0.0/docs/Effect.Exception) gives you the tools to handle these errors.

**Comment by hdgarrood** [comment]
This is not a bad place for this discussion, although perhaps Discourse might be better.

The issue of whether IO actions should indicate explicitly in their types whether they throw exceptions and what kind of exceptions they throw is a hotly contested issue with plenty of previous discussion in the Haskell world, but there are (imo) strong arguments in favour of the current API. See for example https://www.fpcomplete.com/blog/2016/11/exceptions-best-practices-haskell and the things it links to. (Note that `IO` in Haskell is a little bit different from our `Effect`, but I think the same arguments apply in this case.)

I also don't agree that `Either Error a` is the conventional return type of something that might have an error, in either Haskell or PureScript. Not only is "this might fail" part of the contract of `IO` and of `Effect` (see above), but also in code which doesn't concern itself with IO you have plenty of options:

* `MonadError e m => m a`
* `Either SomeSpecificErrorType a`, that is, using an error type which is specific to that particular case
* `Maybe a`
* Something involving `ExceptT`

and probably others.

**Comment by cprussin** [comment]
That's a great article. So if I'm understanding correctly, basically the idea is, explicit errors are unnecessary in the type signature because the contract of `IO` (and `Effect`) is that it _always_ carries the possibility of exception? That makes sense, and many thanks for the pointers.

**Comment by hdgarrood** [comment]
Welcome :) Yes, that’s exactly it.
