### ISSUE TITLE
ReadStreamOptions missing options

### ISSUE THREAD

**Issue by Woody88** [purescript-node/purescript-node-fs#44]
Hi,

I was trying to pass a range to `createReadStreamWith`, however, I couldn't find the `start` and `end` options in the `ReadStreamOptions`. Will you accept a PR for this?

Reference:
https://nodejs.org/api/fs.html#fs_fs_createreadstream_path_options

**Comment by garyb** [comment]
Sounds good to me :+1:

**Comment by Woody88** [comment]
Hi @garyb, 

I would like to hear your opinion about something. 

There are some options that we should not pass default values because they are already set by the object, for example, `start` and `end`. I don't want  to set default values in `defaultReadStreamOptions`  nor `defaultWriteStreamOptions` for some of these options.  

Actually, I think that `start` and `end` options are the only ones that are making me hesitating a bit. I want to add a new type say `data StreamRange = StreamRange Int Int` which will act as the start and end but I think that it might be better to introduce it in the `node-streams` package with a new function that would be called `range :: StreamRange -> Stream row -> Stream row`.

Aside from that the only two options that won't be needed are `encoding` and `fs`. We have `onDataString` and `writeString` in the `node-streams` package, and they both have `Encoding` as a parameter.

What do you think?

**Comment by hdgarrood** [comment]
There are a few approaches. We could use the Prim.Row classes, we could use https://pursuit.purescript.org/packages/purescript-options/5.0.0, or we could use https://pursuit.purescript.org/packages/purescript-option/1.0.0. There are probably other options too. I can't remember what the purescript-node packages usually do for this sort of thing.
