### ISSUE TITLE
Remove redundant/impure `StatsObj` `Fn0` methods

### ISSUE THREAD

**Issue by pete-murphy** [purescript-node/purescript-node-fs#71]
Each of these methods https://github.com/purescript-node/purescript-node-fs/blob/a9da8b9860f8a1f67e38701f5cce72a0f2c3901d/src/Node/FS/Stats.purs#L35-L40 has a corresponding standalone `Stats -> Boolean` function so they seem redundant, and using the `isDirectory :: Fn0 Boolean` directly resulted in this issue https://github.com/aristanetworks/purescript-backend-optimizer/issues/35 because `this` context wasn't preserved after compilation.

**Comment by ptrfrncsmrph** [comment]
A minimal example that produces runtime error (without going through `purs-backend-es`)
```haskell
main :: Effect Unit
main = do
  isDir <- runFn0 <<< (case _ of Stats statsObj -> statsObj.isDirectory) <$> stat "."
  if isDir then
    log "Directory"
  else log "Not directory"
```
fails with
```
❯ spago run
purs compile: No files found using pattern: test/**/*.purs
[info] Build succeeded.
[warn] None of your project files import modules from some projects that are in the direct dependencies of your project.
These dependencies are unused. To fix this warning, remove the following packages from the list of dependencies in your config:
- either
node:internal/fs/utils:416
  return this._checkModeProperty(S_IFDIR);
              ^

TypeError: Cannot read properties of undefined (reading '_checkModeProperty')
    at StatsBase.isDirectory (node:internal/fs/utils:416:15)
```
